### ISSUE TITLE
Build error on linux

### ISSUE THREAD

**Issue by OmniBlade** [GameProgressive/ModuleDevelopmentKit#5]
I get an error with an undeclared symbol as follows:

ModuleDevelopmentKit/TemplateServer.cpp:76:85: error: ‘libuv_callback_on_server_udp_new_connection’ was not declared in this scope

Is the function missing?

**Comment by arves100** [comment]
Thanks, it was a misspelled function. Fixed in https://github.com/GameProgressive/ModuleDevelopmentKit/commit/abd89e5ee0d10dbe3185e7d12921e0fa97596526
